ARG PYTHON_BUILDER_IMAGE=3.12

## ---------------------------------------------------------------------------------- ##
## ------------------------- Python base -------------------------------------------- ##
## ---------------------------------------------------------------------------------- ##
FROM python:latest as python-base

ENV PIP_DEFAULT_TIMEOUT=100 \
  PIP_DISABLE_PIP_VERSION_CHECK=1 \
  PIP_NO_CACHE_DIR=1 \
  PIP_ROOT_USER_ACTION=ignore \
  PYTHONDONTWRITEBYTECODE=1 \
  PYTHONUNBUFFERED=1 \
  PYTHONFAULTHANDLER=1 \
  PYTHONHASHSEED=random \
  LANG=C.UTF-8 \
  LC_ALL=C.UTF-8

RUN apt update \
  && apt upgrade -y \
  && apt-get autoremove -y \
  && apt-get clean -y \
  && rm -rf /root/.cache /var/apt/lists/* /var/cache/apt/* \
  && apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false

## ---------------------------------------------------------------------------------- ##
## ------------------------- Python build base -------------------------------------- ##
## ---------------------------------------------------------------------------------- ##
FROM python-base as build-base

# Install build dependencies
RUN apt-get install -y --no-install-recommends build-essential curl \
  && apt-get autoremove -y \
  && apt-get clean -y \
  && rm -rf /root/.cache /var/apt/lists/* /var/cache/apt/* \
  && apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false

# Install hatch
ADD https://github.com/pypa/hatch/releases/latest/download/hatch-x86_64-unknown-linux-gnu.tar.gz /tmp
RUN tar -C /usr/local/bin -xzf /tmp/hatch-x86_64-unknown-linux-gnu.tar.gz

# Install the rust toolchain
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
ENV PATH="/root/.cargo/bin:${PATH}"

# Install just
RUN cargo install just

## ---------------------------------------------------------------------------------- ##
## ------------------------- Build application -------------------------------------- ##
## ---------------------------------------------------------------------------------- ##
FROM build-base as build-stage

CMD ["tail", "-f", "/dev/null"]
